apiVersion: v1
kind: Service
metadata:
  name: test-github-actions
spec:
  selector:
    app: test-github-actions
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
#  clusterIP: 10.8.0.108
#  externalTrafficPolicy: Cluster
#  ports:
#    - nodePort: 32707
#      port: 80
#      protocol: TCP
#      targetPort: 8080
#  selector:
#    app: test-github-actions
#  sessionAffinity: None
#  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#      - ip: 104.197.111.35
